const key='millfix_issues_v1';
const equipment=[
['CM-PAY-001','Payoff Reel','Entry'],['CM-S1-001','Stand 1','Cold Mill'],['CM-S2-001','Stand 2','Cold Mill'],['CM-S3-001','Stand 3','Cold Mill'],['CM-S4-001','Stand 4','Cold Mill'],['CM-S5-001','Stand 5','Cold Mill'],['CM-ENT-001','Entry Section','Entry'],['CM-EXT-001','Exit Section','Exit'],['CM-TEN-001','Exit Tension Reel','Exit'],['CM-HYD-001','Hydraulic Systems','Maintenance'],['CM-DRV-001','Main Drives','Electrical'],['CM-CLT-001','Coolant System','Process']];
let issues=JSON.parse(localStorage.getItem(key)||'[]');
const app=document.getElementById('app');
function save(){localStorage.setItem(key,JSON.stringify(issues));}
function render(){app.innerHTML=`<header><h1>MillFix</h1><p>Cold Mill Equipment Issue Reporting</p></header><main class="wrap"><div class="nav"><button class="btn primary" onclick="home()">Home</button><button class="btn secondary" onclick="report()">Report Problem</button><button class="btn secondary" onclick="queue()">Maintenance</button></div><section id="view"></section></main>`;home()}
function home(){document.getElementById('view').innerHTML=`<div class="card"><div class="small">Open issues</div><div class="stat">${issues.filter(x=>!['COMPLETED','CLOSED'].includes(x.status)).length}</div><p class="muted">Test the workflow by creating an equipment issue.</p><button class="btn primary" onclick="report()">+ Report a Problem</button></div><div class="card"><h2>Recent Issues</h2>${issues.length?issues.slice().reverse().slice(0,5).map(issueHtml).join(''):'<p class="muted">No issues reported yet.</p>'}</div>`}
function issueHtml(x){return `<div class="issue"><h3>${x.title||x.category}</h3><div>${x.equipmentName} <span class="pill">${x.priority}</span></div><div class="muted">${x.description||''}</div><div class="small">${x.status} · ${new Date(x.createdAt).toLocaleString()}</div></div>`}
function report(){document.getElementById('view').innerHTML=`<div class="card"><h2>Report a Problem</h2><div class="field"><label>Equipment</label><select id="eq">${equipment.map(e=>`<option value="${e[0]}">${e[1]} — ${e[0]}</option>`).join('')}</select></div><div class="field"><label>Priority</label><select id="priority"><option>Normal</option><option>Low</option><option>High</option><option>Critical</option></select></div><div class="field"><label>Problem category</label><select id="category"><option>Mechanical</option><option>Electrical</option><option>Hydraulic</option><option>Automation / Controls</option><option>Coolant / Process</option><option>Safety</option><option>Other</option></select></div><div class="field"><label>Title</label><input id="title" placeholder="Short description"></div><div class="field"><label>Details</label><textarea id="desc" placeholder="Describe what is happening, when it happens, and anything you've observed."></textarea></div><div class="field"><label>Photo</label><input id="photo" type="file" accept="image/*" capture="environment"></div><button class="btn primary" onclick="submitIssue()">Submit Issue</button></div>`}
function submitIssue(){const id=document.getElementById('eq').value,e=equipment.find(x=>x[0]===id);const issue={id:'ISS-'+String(Date.now()).slice(-7),equipmentId:id,equipmentName:e[1],department:e[2],priority:document.getElementById('priority').value,category:document.getElementById('category').value,title:document.getElementById('title').value||document.getElementById('category').value,description:document.getElementById('desc').value,status:'NEW',createdAt:new Date().toISOString()};issues.push(issue);save();document.getElementById('view').innerHTML=`<div class="card"><div class="success"><b>Issue submitted.</b><br>${issue.id} was routed to ${issue.department}.</div><button class="btn primary" onclick="home()">Back to Home</button></div>`}
function queue(){document.getElementById('view').innerHTML=`<div class="card"><h2>Maintenance Queue</h2>${issues.length?issues.slice().reverse().map(x=>`<div class="issue"><h3>${x.id} — ${x.equipmentName}</h3><div>${x.title} <span class="pill">${x.priority}</span></div><div class="muted">${x.department} · ${x.category}</div><div class="field"><select onchange="setStatus('${x.id}',this.value)"><option ${x.status==='NEW'?'selected':''}>NEW</option><option ${x.status==='ASSIGNED'?'selected':''}>ASSIGNED</option><option ${x.status==='IN_PROGRESS'?'selected':''}>IN_PROGRESS</option><option ${x.status==='WAITING_FOR_PARTS'?'selected':''}>WAITING_FOR_PARTS</option><option ${x.status==='COMPLETED'?'selected':''}>COMPLETED</option><option ${x.status==='CLOSED'?'selected':''}>CLOSED</option></select></div></div>`).join(''):'<p class="muted">No issues yet.</p>'}</div>`}
function setStatus(id,status){const x=issues.find(i=>i.id===id);if(x){x.status=status;save();queue()}}
if('serviceWorker' in navigator) window.addEventListener('load',()=>navigator.serviceWorker.register('sw.js').catch(()=>{}));
render();
